# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1326, 726)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.radioButton_11 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_11.setEnabled(True)
        self.radioButton_11.setGeometry(QtCore.QRect(20, 470, 117, 22))
        self.radioButton_11.setAutoExclusive(False)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.radioButton_13 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_13.setGeometry(QtCore.QRect(20, 150, 117, 22))
        self.radioButton_13.setAutoExclusive(False)
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.radioButton_17 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_17.setGeometry(QtCore.QRect(20, 230, 117, 22))
        self.radioButton_17.setAutoExclusive(False)
        self.radioButton_17.setObjectName(_fromUtf8("radioButton_17"))
        self.radioButton_19 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_19.setGeometry(QtCore.QRect(20, 290, 117, 22))
        self.radioButton_19.setAutoExclusive(False)
        self.radioButton_19.setObjectName(_fromUtf8("radioButton_19"))
        self.radioButton_5 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 350, 117, 22))
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.radioButton_14 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_14.setGeometry(QtCore.QRect(20, 170, 117, 22))
        self.radioButton_14.setAutoExclusive(False)
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.radioButton_9 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_9.setGeometry(QtCore.QRect(20, 430, 117, 22))
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.graphicsView_3 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_3.setGeometry(QtCore.QRect(160, 377, 461, 271))
        self.graphicsView_3.setObjectName(_fromUtf8("graphicsView_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 350, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.radioButton_10 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_10.setGeometry(QtCore.QRect(20, 450, 117, 22))
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 46, 51, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 130, 117, 22))
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(160, 87, 461, 261))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 50, 331, 27))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(950, 650, 131, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.radioButton_3 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 310, 117, 22))
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_8 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(20, 410, 117, 22))
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.radioButton_18 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_18.setGeometry(QtCore.QRect(20, 250, 117, 22))
        self.radioButton_18.setAutoExclusive(False)
        self.radioButton_18.setObjectName(_fromUtf8("radioButton_18"))
        self.radioButton_15 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_15.setGeometry(QtCore.QRect(20, 190, 117, 22))
        self.radioButton_15.setAutoExclusive(False)
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.radioButton_21 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_21.setGeometry(QtCore.QRect(20, 510, 117, 22))
        self.radioButton_21.setAutoExclusive(False)
        self.radioButton_21.setObjectName(_fromUtf8("radioButton_21"))
        self.radioButton_20 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_20.setGeometry(QtCore.QRect(20, 270, 117, 22))
        self.radioButton_20.setAutoExclusive(False)
        self.radioButton_20.setObjectName(_fromUtf8("radioButton_20"))
        self.radioButton_7 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(20, 390, 117, 22))
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.radioButton_4 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 330, 117, 22))
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioButton_12 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_12.setGeometry(QtCore.QRect(20, 490, 117, 22))
        self.radioButton_12.setAutoExclusive(False)
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.radioButton_6 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(20, 370, 117, 22))
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.radioButton_16 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_16.setGeometry(QtCore.QRect(20, 210, 117, 22))
        self.radioButton_16.setAutoExclusive(False)
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(20, 90, 117, 22))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 650, 101, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 50, 99, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.mplwindow = QtGui.QWidget(self.centralwidget)
        self.mplwindow.setGeometry(QtCore.QRect(650, 10, 651, 641))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setObjectName(_fromUtf8("mplwindow"))
        self.mplvl = QtGui.QVBoxLayout(self.mplwindow)
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.horizontalSlider = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 560, 121, 29))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSingleStep(0)
        self.horizontalSlider.setPageStep(10)
        self.horizontalSlider.setProperty("value", 100)
        self.horizontalSlider.setSliderPosition(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(28, 630, 101, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 540, 121, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(40, 590, 70, 31))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 19, 51, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(81, 15, 211, 27))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(521, 15, 99, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(301, 15, 91, 27))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.dateEdit_2 = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(421, 15, 91, 27))
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(400, 20, 31, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.stop_button = QtGui.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(520, 50, 99, 27))
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1326, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.radioButton_11.setText(_translate("MainWindow", "Sofa", None))
        self.radioButton_13.setText(_translate("MainWindow", "Bicycle", None))
        self.radioButton_17.setText(_translate("MainWindow", "Bus", None))
        self.radioButton_19.setText(_translate("MainWindow", "Chair", None))
        self.radioButton_5.setText(_translate("MainWindow", "Dog", None))
        self.radioButton_14.setText(_translate("MainWindow", "Bird", None))
        self.radioButton_9.setText(_translate("MainWindow", "Potted plant", None))
        self.label.setText(_translate("MainWindow", "Uploaded Image", None))
        self.radioButton_10.setText(_translate("MainWindow", "Sheep", None))
        self.label_4.setText(_translate("MainWindow", "Single", None))
        self.radioButton_2.setText(_translate("MainWindow", "Aeroplane", None))
        self.label_3.setText(_translate("MainWindow", "Co-Location Graph", None))
        self.radioButton_3.setText(_translate("MainWindow", "Cow", None))
        self.radioButton_8.setText(_translate("MainWindow", "Person", None))
        self.radioButton_18.setText(_translate("MainWindow", "Car", None))
        self.radioButton_15.setText(_translate("MainWindow", "Boat", None))
        self.radioButton_21.setText(_translate("MainWindow", "Tv", None))
        self.radioButton_20.setText(_translate("MainWindow", "Cat", None))
        self.radioButton_7.setText(_translate("MainWindow", "Motorbike", None))
        self.radioButton_4.setText(_translate("MainWindow", "Dining Table", None))
        self.radioButton_12.setText(_translate("MainWindow", "Train", None))
        self.radioButton_6.setText(_translate("MainWindow", "Horse", None))
        self.radioButton_16.setText(_translate("MainWindow", "Bottle", None))
        self.radioButton.setText(_translate("MainWindow", "All", None))
        self.label_2.setText(_translate("MainWindow", "Tagged Image", None))
        self.pushButton.setText(_translate("MainWindow", "Upload", None))
        self.pushButton_2.setText(_translate("MainWindow", "Update", None))
        self.label_5.setText(_translate("MainWindow", "Edge Threshold", None))
        self.label_6.setText(_translate("MainWindow", "Batch", None))
        self.pushButton_3.setText(_translate("MainWindow", "Upload", None))
        self.label_7.setText(_translate("MainWindow", "To", None))
        self.stop_button.setText(_translate("MainWindow", "Stop", None))

