# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CBIR_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1328, 735)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 320, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.radioButton_4 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 300, 117, 22))
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioButton_9 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_9.setGeometry(QtCore.QRect(30, 400, 117, 22))
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.radioButton_13 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_13.setGeometry(QtCore.QRect(30, 120, 117, 22))
        self.radioButton_13.setAutoExclusive(False)
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.radioButton_18 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_18.setGeometry(QtCore.QRect(30, 220, 117, 22))
        self.radioButton_18.setAutoExclusive(False)
        self.radioButton_18.setObjectName(_fromUtf8("radioButton_18"))
        self.radioButton_12 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_12.setGeometry(QtCore.QRect(30, 460, 117, 22))
        self.radioButton_12.setAutoExclusive(False)
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.radioButton_15 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_15.setGeometry(QtCore.QRect(30, 160, 117, 22))
        self.radioButton_15.setAutoExclusive(False)
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 20, 351, 27))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 100, 117, 22))
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_21 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_21.setGeometry(QtCore.QRect(30, 480, 117, 22))
        self.radioButton_21.setAutoExclusive(False)
        self.radioButton_21.setObjectName(_fromUtf8("radioButton_21"))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(170, 57, 381, 261))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.radioButton_11 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_11.setEnabled(True)
        self.radioButton_11.setGeometry(QtCore.QRect(30, 440, 117, 22))
        self.radioButton_11.setAutoExclusive(False)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.radioButton_20 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_20.setGeometry(QtCore.QRect(30, 240, 117, 22))
        self.radioButton_20.setAutoExclusive(False)
        self.radioButton_20.setObjectName(_fromUtf8("radioButton_20"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(38, 600, 101, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.graphicsView_3 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_3.setGeometry(QtCore.QRect(170, 347, 381, 271))
        self.graphicsView_3.setObjectName(_fromUtf8("graphicsView_3"))
        self.radioButton_19 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_19.setGeometry(QtCore.QRect(30, 260, 117, 22))
        self.radioButton_19.setAutoExclusive(False)
        self.radioButton_19.setObjectName(_fromUtf8("radioButton_19"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 20, 99, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalSlider = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 530, 121, 29))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSingleStep(0)
        self.horizontalSlider.setPageStep(10)
        self.horizontalSlider.setProperty("value", 100)
        self.horizontalSlider.setSliderPosition(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.radioButton_6 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(30, 340, 117, 22))
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(50, 560, 70, 31))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.radioButton_10 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_10.setGeometry(QtCore.QRect(30, 420, 117, 22))
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 510, 121, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 16, 51, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.radioButton_5 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(30, 320, 117, 22))
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.radioButton_7 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(30, 360, 117, 22))
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.radioButton_14 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_14.setGeometry(QtCore.QRect(30, 140, 117, 22))
        self.radioButton_14.setAutoExclusive(False)
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.radioButton_8 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(30, 380, 117, 22))
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.radioButton_17 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_17.setGeometry(QtCore.QRect(30, 200, 117, 22))
        self.radioButton_17.setAutoExclusive(False)
        self.radioButton_17.setObjectName(_fromUtf8("radioButton_17"))
        self.radioButton_16 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_16.setGeometry(QtCore.QRect(30, 180, 117, 22))
        self.radioButton_16.setAutoExclusive(False)
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.radioButton_3 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 280, 117, 22))
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(30, 60, 117, 22))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(570, 20, 741, 611))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget.setIconSize(QtCore.QSize(10, 10))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(330)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(300)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1328, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Uploaded Image", None))
        self.radioButton_4.setText(_translate("MainWindow", "Dining Table", None))
        self.radioButton_9.setText(_translate("MainWindow", "Potted plant", None))
        self.radioButton_13.setText(_translate("MainWindow", "Bicycle", None))
        self.radioButton_18.setText(_translate("MainWindow", "Car", None))
        self.radioButton_12.setText(_translate("MainWindow", "Train", None))
        self.radioButton_15.setText(_translate("MainWindow", "Boat", None))
        self.radioButton_2.setText(_translate("MainWindow", "Aeroplane", None))
        self.radioButton_21.setText(_translate("MainWindow", "Tv", None))
        self.radioButton_11.setText(_translate("MainWindow", "Sofa", None))
        self.radioButton_20.setText(_translate("MainWindow", "Cat", None))
        self.pushButton_2.setText(_translate("MainWindow", "Update", None))
        self.radioButton_19.setText(_translate("MainWindow", "Chair", None))
        self.pushButton.setText(_translate("MainWindow", "Upload", None))
        self.radioButton_6.setText(_translate("MainWindow", "Horse", None))
        self.radioButton_10.setText(_translate("MainWindow", "Sheep", None))
        self.label_5.setText(_translate("MainWindow", "Edge Threshold", None))
        self.label_4.setText(_translate("MainWindow", "Single", None))
        self.radioButton_5.setText(_translate("MainWindow", "Dog", None))
        self.radioButton_7.setText(_translate("MainWindow", "Motorbike", None))
        self.radioButton_14.setText(_translate("MainWindow", "Bird", None))
        self.radioButton_8.setText(_translate("MainWindow", "Person", None))
        self.radioButton_17.setText(_translate("MainWindow", "Bus", None))
        self.radioButton_16.setText(_translate("MainWindow", "Bottle", None))
        self.radioButton_3.setText(_translate("MainWindow", "Cow", None))
        self.radioButton.setText(_translate("MainWindow", "All", None))
        self.tableWidget.setSortingEnabled(False)

